app = 'yorubatts-bot'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
